[language-server.zls]
# omit the following line if `zls` is in your PATH
command = "/usr/bin/zls"
# There are two ways to set config options:
#   - edit your `zls.json` that applies to any editor that uses ZLS
#   - set in-editor config options with the `config.zls.<name>` fields below.
#
# Further information on how to configure ZLS:
# https://zigtools.org/zls/configure/

# Whether to enable build-on-save diagnostics
#
# Further information about build-on save:
# https://zigtools.org/zls/guides/build-on-save/
# config.zls.enable_build_on_save = true

# omit the following line if `zig` is in your PATH
config.zls.zig_exe_path = "/usr/bin/zig"
